-- View: fps.vcontractproject

CREATE OR REPLACE VIEW fps.vcontractproject AS
 SELECT parentproject,
    projecttitle,
    program,
    customer,
    manager,
    transferincome,
    custincome,
    wip_eoy,
    wip_limit,
    wip_current,
    projectstatus,
    costbookno,
    datecreated,
    feccost,
    profit,
    budget_cvl,
    datecosted,
    disease,
    contract,
    projectparent,
    shorttitle,
    caseworksub,
    pvsincome,
    plancaseworkdebit,
    finished,
    owningrc,
    comments,
    carryover,
    carryoverseed,
    isdefraproject,
    costcentre,
    oracleprojectcode,
    subaccountcode,
    projectgroup,
    incomeaccountcode,
    fpsyear
   FROM fps.tlkpproject p
   JOIN fps.vtblcontract c ON c.contractno = p.contract AND c.fpsyear = p.fpsyear;
