-- View: fps.vprojectmonthfinal_paycosts
CREATE OR REPLACE VIEW fps.vprojectmonthfinal_paycosts AS
 SELECT projectmonthfinal.monthno,
    projectmonthfinal.periodname,
    projectmonthfinal.cumflag,
    projectmonthfinal.costprofile,
    projectmonthfinal.subcontracts,
    projectmonthfinal.animals,
    projectmonthfinal.nonanimals,
    (projectmonthfinal.timecosts)::numeric AS timecosts,
    projectmonthfinal.transfercosts,
    (((projectmonthfinal.totalcost)::numeric - (projectmonthfinal.timecosts)::numeric) + (projectmonthfinal.paycosts)::numeric) AS totalcost,
    (projectmonthfinal.invoices)::numeric AS invoices,
    projectmonthfinal.coiw,
    projectmonthfinal.portsales,
    (((COALESCE((projectmonthfinal.cumcost)::numeric, (0)::numeric) + COALESCE((projectmonthfinal.cumpaycosts)::numeric, (0)::numeric)))::double precision - COALESCE(sum(timecostcalcs.cost), (0)::double precision)) AS cumcost,
    projectmonthfinal.cumprofile,
    projectmonthfinal.sumofcostprofile,
    (projectmonthfinal.cuminvoices)::numeric AS cuminvoices,
    projectmonthfinal.cumcoiw,
    projectmonthfinal.cumportsales,
    projectmonthfinal.mstonedue,
    projectmonthfinal.due__done,
    projectmonthfinal.ontime,
    projectmonthfinal.sumofmstonedue,
    projectmonthfinal.sumofdue__done,
    projectmonthfinal.sumofontime,
    projectmonthfinal.cwdebit,
    projectmonthfinal.cwcredit,
    projectmonthfinal.cumcwdebit,
    projectmonthfinal.cumcwcredit,
    projectmonthfinal.totalhours,
    projectmonthfinal.cumtotalhours,
    (projectmonthfinal.cumsubcontracts)::numeric AS cumsubcontracts,
    (projectmonthfinal.cumtestcosts)::numeric AS cumtestcosts,
    projectmonthfinal.project,
    (projectmonthfinal.paycosts)::numeric AS payratecosts,
    projectmonthfinal.fpsyear
   FROM (fps.projectmonthfinal
     LEFT JOIN fps.timecostcalcs ON ((((projectmonthfinal.project)::text = (timecostcalcs.project)::text) AND (projectmonthfinal.monthno = timecostcalcs.month) AND projectmonthfinal.fpsyear = timecostcalcs.fpsyear)))
  GROUP BY projectmonthfinal.monthno, projectmonthfinal.periodname, projectmonthfinal.cumflag, projectmonthfinal.costprofile, projectmonthfinal.subcontracts, projectmonthfinal.animals, projectmonthfinal.nonanimals, ((projectmonthfinal.timecosts)::numeric), projectmonthfinal.transfercosts, ((projectmonthfinal.totalcost)::numeric), ((projectmonthfinal.invoices)::numeric), projectmonthfinal.coiw, projectmonthfinal.portsales, projectmonthfinal.cumprofile, projectmonthfinal.sumofcostprofile, ((projectmonthfinal.cuminvoices)::numeric), projectmonthfinal.cumcoiw, projectmonthfinal.cumportsales, projectmonthfinal.mstonedue, projectmonthfinal.due__done, projectmonthfinal.ontime, projectmonthfinal.sumofmstonedue, projectmonthfinal.sumofdue__done, projectmonthfinal.sumofontime, projectmonthfinal.cwdebit, projectmonthfinal.cwcredit, projectmonthfinal.cumcwdebit, projectmonthfinal.cumcwcredit, projectmonthfinal.totalhours, projectmonthfinal.cumtotalhours, ((projectmonthfinal.cumsubcontracts)::numeric), ((projectmonthfinal.cumtestcosts)::numeric), projectmonthfinal.project, (((projectmonthfinal.totalcost)::numeric - (projectmonthfinal.timecosts)::numeric) + (projectmonthfinal.paycosts)::numeric), ((projectmonthfinal.cumcost)::numeric), ((projectmonthfinal.cumpaycosts)::numeric), ((projectmonthfinal.paycosts)::numeric), projectmonthfinal.fpsyear;
