-- View: fps.vprojectmonthfinal

CREATE OR REPLACE VIEW fps.vprojectmonthfinal AS
 SELECT pmf.project,
    pmf.monthno,
    pmf.periodname,
    pmf.cumflag,
    pmf.costprofile,
    pmf.subcontracts,
    pmf.animals,
    pmf.nonanimals,
    pmf.timecosts,
    pmf.transfercosts,
    pmf.totalcost,
    pmf.invoices,
    pmf.coiw,
    pmf.portsales,
    pmf.cumcost,
    pmf.cumprofile,
    pmf.sumofcostprofile,
    pmf.cuminvoices,
    pmf.cumcoiw,
    pmf.cumportsales,
    pmf.mstonedue,
    pmf.due__done,
    pmf.ontime,
    pmf.sumofmstonedue,
    pmf.sumofdue__done,
    pmf.sumofontime,
    pmf.cwdebit,
    pmf.cwcredit,
    pmf.cumcwdebit,
    pmf.cumcwcredit,
    pmf.totalhours,
    pmf.cumtotalhours,
    pmf.cumsubcontracts,
    pmf.x,
    pmf.cumtestcosts,
    pmf.paycosts,
    pmf.cumpaycosts,
    pmf.fpsyear
   FROM (fps.projectmonthfinal pmf
     JOIN fps.vtlkpproject p ON ((((p.parentproject)::text = (pmf.project)::text) AND (p.fpsyear = pmf.fpsyear))));
