-- View: fps.vtlkpproject

CREATE OR REPLACE VIEW fps.vtlkpproject AS
 SELECT p.parentproject,
    p.projecttitle,
    p.program,
    p.customer,
    p.manager,
    p.transferincome,
    p.custincome,
    p.wip_eoy,
    p.wip_limit,
    p.wip_current,
    p.projectstatus,
    p.costbookno,
    p.datecreated,
    p.feccost,
    p.profit,
    p.budget_cvl,
    p.datecosted,
    p.disease,
    p.contract,
    p.projectparent,
    p.shorttitle,
    p.caseworksub,
    p.pvsincome,
    p.plancaseworkdebit,
    p.finished,
    p.owningrc,
    p.comments,
    p.carryover,
    p.carryoverseed,
    p.isdefraproject,
    p.costcentre,
    p.oracleprojectcode,
    p.subaccountcode,
    p.projectgroup,
    p.incomeaccountcode,
    p.fpsyear
   FROM fps.tlkpproject p
   JOIN fps.vtlkpprogram pr ON pr.programno = p.program AND pr.fpsyear = p.fpsyear;
