<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\ProjectMaintenanceController.cs" />
    <Compile Remove="Controllers\ResourceMgmtReplanController.cs" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
	<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
	<PackageReference Include="AutoMapper" Version="16.1.1" />
	<PackageReference Include="Microsoft.Identity.Web" Version="4.7.0" />
	<PackageReference Include="Microsoft.Identity.Web.UI" Version="4.6.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
	<PackageReference Include="AWSSDK.CloudWatchLogs" Version="4.0.15.3" />
    <PackageReference Include="Serilog.Sinks.AwsCloudWatch" Version="4.4.42" />
	<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.5" />
	<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>    
    <ProjectReference Include="..\..\Apha.Common\Apha.Common.csproj" /> 
    <ProjectReference Include="..\Apha.FPS.Application\Apha.FPS.Application.csproj" />
    <ProjectReference Include="..\Apha.FPS.DataAccess\Apha.FPS.DataAccess.csproj" />
  </ItemGroup>

</Project>
