-- Table: fps.project_log

CREATE TABLE fps.project_log (
    sequenceno integer DEFAULT nextval('fps.project_log_sequenceno_seq'::regclass) NOT NULL,
    parentproject character varying(20) NOT NULL,
    projecttitle character varying(200) NOT NULL,
    program character varying(10) NOT NULL,
    customer character varying(50) NOT NULL,
    manager character varying(50),
    transferincome money NOT NULL,
    custincome money NOT NULL,
    wip_eoy money,
    wip_limit money,
    wip_current money,
    projectstatus character varying(50) NOT NULL,
    costbookno character varying(50),
    datecreated timestamp without time zone,
    feccost money,
    profit money,
    budget_cvl money,
    datecosted timestamp without time zone,
    disease character varying(50) NOT NULL,
    contract character varying(10) NOT NULL,
    projectparent character varying(50),
    shorttitle character varying(30),
    caseworksub numeric(5,4),
    pvsincome money,
    plancaseworkdebit money,
    finished smallint,
    owningrc character varying(50),
    comments text,
    carryover money,
    carryoverseed money,
    date_time timestamp without time zone,
    user_id character varying(20),
    insert_delete character(2),
    jobcode character varying(20) NOT NULL,
    isdefraproject smallint,
    costcentre double precision,
    oracleprojectcode character varying(50),
    subaccountcode character varying(50),
    projectgroup character varying(50),
    incomeaccountcode character varying(50),
    fpsyear integer NOT NULL,
    CONSTRAINT pk_project_log PRIMARY KEY (sequenceno, fpsyear),

    CONSTRAINT fk_project_log_fpsyear FOREIGN KEY (fpsyear) REFERENCES fps.tblyearmaster(fpsyear)
);
