-- Table: fps.tlkpproject

CREATE TABLE fps.tlkpproject (
    parentproject citext NOT NULL,
    projecttitle character varying(200) NOT NULL,
    program citext NOT NULL,
    customer citext NOT NULL,
    manager character varying(50),
    transferincome money NOT NULL,
    custincome money NOT NULL,
    wip_eoy money DEFAULT 0,
    wip_limit money,
    wip_current money,
    projectstatus citext NOT NULL,
    costbookno character varying(50),
    datecreated timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    feccost money DEFAULT 0,
    profit money DEFAULT 0,
    budget_cvl money DEFAULT 0,
    datecosted timestamp without time zone,
    disease citext NOT NULL,
    contract citext DEFAULT 0 NOT NULL,
    projectparent character varying(50),
    shorttitle character varying(30),
    caseworksub numeric(5,4),
    pvsincome money,
    plancaseworkdebit money,
    finished smallint DEFAULT 0,
    owningrc character varying(50),
    comments text,
    carryover money,
    carryoverseed money,
    isdefraproject smallint NOT NULL,
    costcentre double precision,
    oracleprojectcode character varying(50),
    subaccountcode citext,
    projectgroup citext,
    incomeaccountcode citext NOT NULL,
    fpsyear integer NOT NULL,
    CONSTRAINT pk_tlkpproject PRIMARY KEY (parentproject, fpsyear),
    CONSTRAINT fk_tlkpproject_1__10 FOREIGN KEY (projectstatus) REFERENCES fps.tblstatus(status),
    CONSTRAINT fk_tlkpproject_1__16 FOREIGN KEY (customer) REFERENCES fps.tlkpcustomer(customer),
    CONSTRAINT fk_tlkpproject_contract FOREIGN KEY (contract, fpsyear) REFERENCES fps.tblcontract(contractno, fpsyear),
    CONSTRAINT fk_tlkpproject_disease FOREIGN KEY (disease) REFERENCES fps.tbldisease(disease),
    CONSTRAINT fk_tlkpproject_incomeaccountcode FOREIGN KEY (incomeaccountcode) REFERENCES fps.tlkpaccountcode(code),
    CONSTRAINT fk_tlkpproject_subaccountcode FOREIGN KEY (subaccountcode) REFERENCES fps.tlkpsubaccount(subaccountcode),
    CONSTRAINT fk_tlkpproject_fpsyear FOREIGN KEY (fpsyear) REFERENCES fps.tblyearmaster(fpsyear),

    CONSTRAINT fk_tlkpproject_program FOREIGN KEY (program, fpsyear) REFERENCES fps.tlkpprogram(programno, fpsyear),

    CONSTRAINT fk_tlkpproject_projectgroup FOREIGN KEY (projectgroup, fpsyear) REFERENCES fps.tlkpprojectgroup(projectgroup, fpsyear)
);
