<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\ResourceMgmtReplanService.cs" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="AutoMapper" Version="16.1.1" />	  
	<PackageReference Include="Npgsql" Version="10.0.1" />
	<PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Apha.Common\Apha.Common.csproj" />
    <ProjectReference Include="..\Apha.FPS.Core\Apha.FPS.Core.csproj" />
  </ItemGroup>

</Project>
