<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Email\" />
    <Folder Include="ExcelImportExport\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.10" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Apha.Common\Apha.Common.csproj" />
    <ProjectReference Include="..\Apha.FPSApps.Application\Apha.FPSApps.Application.csproj" />
  </ItemGroup>

</Project>
