--liquibase formatted sql

--changeset repo-admin:007_fps.proj_subcontract_staging labels:ddl context:all
 DROP TABLE IF EXISTS fps.proj_subcontract_staging;

CREATE TABLE IF NOT EXISTS fps.proj_subcontract_staging
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    project character varying(20) COLLATE pg_catalog."default",
    testjob character varying(50) COLLATE pg_catalog."default",
    month character varying(10) COLLATE pg_catalog."default",
    amount character varying(10) COLLATE pg_catalog."default",
    workgroup character varying(50) COLLATE pg_catalog."default",
    acctcode character varying(30) COLLATE pg_catalog."default",
    supplier character varying(50) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    suppliernumber character varying(10) COLLATE pg_catalog."default",
    dailyrate character varying(10) COLLATE pg_catalog."default",
    animaldays character varying(10) COLLATE pg_catalog."default",
    filename character varying(255) COLLATE pg_catalog."default",
    importedby character varying(255) COLLATE pg_catalog."default",
    importeddate timestamp without time zone,
    validationfailure text COLLATE pg_catalog."default",
    isexported boolean DEFAULT false,
    ispassed boolean DEFAULT false,
    CONSTRAINT pk_proj_subcontract_staging PRIMARY KEY (id)
)

TABLESPACE pg_default;

--rollback DROP TABLE IF EXISTS fps.proj_subcontract_staging;