<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <AssemblyName>Apha.FPSApps.Web</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="AutoMapper" Version="16.1.1" />	
	<PackageReference Include="Microsoft.Identity.Web" Version="4.7.0" />
	<PackageReference Include="Microsoft.Identity.Web.UI" Version="4.7.0" />
	<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
	<PackageReference Include="AWSSDK.CloudWatchLogs" Version="4.0.15.3" />
    <PackageReference Include="Serilog.Sinks.AwsCloudWatch" Version="4.4.42" />
	<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.5" />
	<PackageReference Include="ClosedXML" Version="0.105.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Apha.Common\Apha.Common.csproj" />
    <ProjectReference Include="..\Apha.FPSApps.Application\Apha.FPSApps.Application.csproj" />
    <ProjectReference Include="..\Apha.FPSApps.Infrastructure\Apha.FPSApps.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\FPS\Views\YearMaster\" />
    <Folder Include="Filters\" />
    <Folder Include="Utilities\" />
  </ItemGroup>

</Project>
