using Apha.BatchJobs.Domain.Entities;
using Apha.BatchJobs.Domain.Enums;

namespace Apha.BatchJobs.Domain.Interfaces;

/// <summary>
/// Repository for managing job execution records and history.
/// </summary>
public interface IJobExecutionRepository
{
    /// <summary>
    /// Records the start of a job execution.
    /// </summary>
    /// <param name="record">The execution record to create.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The ID of the created execution record.</returns>
    Task<int> CreateExecutionRecordAsync(JobExecutionRecord record, CancellationToken cancellationToken = default);

    /// <summary>
    /// Updates an existing execution record.
    /// </summary>
    /// <param name="record">The execution record to update.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task UpdateExecutionRecordAsync(JobExecutionRecord record, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets the last execution record for a given job.
    /// </summary>
    /// <param name="jobName">The name of the job.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task<JobExecutionRecord?> GetLastExecutionAsync(string jobName, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets an execution record by its external execution identifier.
    /// </summary>
    /// <param name="jobExecutionId">External job execution id.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task<JobExecutionRecord?> GetExecutionByJobExecutionIdAsync(Guid jobExecutionId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Creates a new job queue record in Initiated state.
    /// Called by the API immediately after accepting a trigger request,
    /// before publishing the EventBridge event.
    /// </summary>
    /// <param name="jobName">Canonical job name (no spaces).</param>
    /// <param name="jobExecutionId">Correlation GUID generated by the API.</param>
    /// <param name="requestedBy">Identity of the caller.</param>
    /// <param name="requestedAtUtc">UTC timestamp when the API accepted the request.</param>
    /// <param name="runMode">Manual or Scheduled.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The JobQueueId of the newly created record.</returns>
    Task<Guid> CreateInitiatedRecordAsync(
        string jobName,
        Guid jobExecutionId,
        string requestedBy,
        DateTime requestedAtUtc,
        RunMode runMode,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Ensures baseline status rows exist in fps.job_status for all known jobs in fps.job_master.
    /// </summary>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task EnsureJobStatusCatalogAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Tries to persist an idempotent cancellation request keyed by job execution id.
    /// </summary>
    /// <param name="jobExecutionId">External job execution id.</param>
    /// <param name="requestedBy">Identity that requested cancellation.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>
    /// True when cancellation is newly requested; false when an existing request is already stored.
    /// </returns>
    Task<bool> TryRequestCancellationAsync(Guid jobExecutionId, string requestedBy, CancellationToken cancellationToken = default);

    /// <summary>
    /// Creates a durable cancellation request when none exists.
    /// </summary>
    /// <param name="jobExecutionId">External job execution id.</param>
    /// <param name="requestedBy">Identity that requested cancellation.</param>
    /// <param name="source">Optional source channel (UI/API/system).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>
    /// True when request is newly persisted; false when request already exists.
    /// </returns>
    Task<bool> UpsertCancellationRequestAsync(
        Guid jobExecutionId,
        string requestedBy,
        string? source = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets durable cancellation request details for a given execution id.
    /// </summary>
    /// <param name="jobExecutionId">External job execution id.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task<CancellationRequestRecord?> GetCancellationRequestAsync(Guid jobExecutionId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Marks a durable cancellation request as consumed by a worker.
    /// </summary>
    /// <param name="jobExecutionId">External job execution id.</param>
    /// <param name="consumedBy">Worker identity consuming the request.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task MarkCancellationConsumedAsync(Guid jobExecutionId, string consumedBy, CancellationToken cancellationToken = default);

    /// <summary>
    /// Returns true when a cancellation request exists for the given execution id.
    /// </summary>
    /// <param name="jobExecutionId">External job execution id.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task<bool> IsCancellationRequestedAsync(Guid jobExecutionId, CancellationToken cancellationToken = default);
}
