using Apha.Common.BulkRates.Validation;
using Apha.FPS.Core.Entities.BulkRates;

namespace Apha.FPS.Application.Services
{
    /// <summary>
    /// Intermediate result returned by BulkRatesExcelParser.
    /// Contains parsed (but not yet validated) staging rows for all four streams.
    /// </summary>
    public record BulkRatesParseResult
    {
        public string JobName { get; init; } = string.Empty;
        public Guid JobQueueId { get; init; }

        // FEC / Test stream
        public IReadOnlyList<FecStagingRow> FecRows { get; init; } = [];
        public IReadOnlyList<AgrupStagingRow> AgrupRows { get; init; } = [];

        // Staff stream
        public IReadOnlyList<StaffStagingRow> StaffRows { get; init; } = [];

        // Animal stream
        public IReadOnlyList<AnimalStagingRow> AnimalRows { get; init; } = [];

        /// <summary>File-level parse errors (missing worksheet, wrong columns, etc.).</summary>
        public IReadOnlyList<string> ParseErrors { get; init; } = [];

        public bool HasParseErrors => ParseErrors.Count > 0;

        /// <summary>
        /// DR-VAL-03: key/value pairs read from the workbook's protected metadata sheet
        /// (_BulkRatesMetadata, VeryHidden). Empty when the sheet is absent (e.g. a workbook
        /// not generated by this system) or for non-snapshot job types.
        /// </summary>
        public IReadOnlyDictionary<string, string> WorkbookMetadata { get; init; } =
            new Dictionary<string, string>();
    }

    /// <summary>Result returned by BulkRatesValidator after running all checks.</summary>
    public class BulkRatesValidationResult
    {
        public IReadOnlyList<StagingValidationError> Errors { get; init; } = [];
        public BulkRatesRowCounts RowCounts { get; init; } = new();
    }

    /// <summary>
    /// DR-API-07: output of BulkRatesValidator.BuildFreezeAsync — the release-time
    /// re-validation's blocking findings (if any) plus, when clean, the per-row
    /// classification to freeze onto staging (CR056) via
    /// IBulkRatesRepository.FreezeStagingCalculatedActionsAsync.
    /// </summary>
    public sealed record BulkRatesFreezeResult
    {
        public IReadOnlyList<ValidationFinding> BlockingErrors { get; init; } = [];
        public IReadOnlyList<BulkRatesFreezeEntry> FecFreezes { get; init; } = [];
        public IReadOnlyList<BulkRatesFreezeEntry> AgrupFreezes { get; init; } = [];
    }
}
